### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by ash2x3zb9cy** [ashbc/tgrsite#2]
* [x] PASSWORD CHANGING AND FORGOTTEN REQUESTS
* [x] Create user groups such that non-superusers can use the admin site
* [x] stuff that was completed before this list existed
* [ ] Forum
  * [x] Edit threads!
  * [x] Edit responses
  * [ ] Migrate old uwcs forums if possible
  * [ ] Improve time-related stuff
    * [x] "Latest post/response" on subforums
    * [ ] "Recent posts/comments" like old site?
* [ ] Messaging
  * [x] Send to individual threads (as opposed to "quick dm")
  * [x] Thread detail page
  * [ ] Improve Quick DM
    * [ ] Add typeahead
  * [ ] Add mini forms to list page <- clarify?
  * [ ] Group chats have been disabled until UI has been made for the new system.
* [ ] RPGs
  * [x] Manage RPGs (delete/edit)
  * [x] Sign-up and leave as player
  * [x] View RPG members
  * [x] Member management (add/remove players from your games)
  * [ ] Comments (see #1)
  * [x] Do away with the selection options for RPG timeslot (See #3)
* [x] Users
  * [x] Parse markdown for bios
* [x] Minor Bugs
  * [x] There's a tag inside the RPG detail view that doesn't close. Repr: add two RPGs and see how the second one is all bold.
* [ ] Standardise error messages
* [ ] Tinker with database config
* [ ] Polls

Future Features:
* [ ] Notifications & Email system!
  * [x] Well, emails are basically necessary, so we need to sort out an SMTP server. Password reset emails are currently written to a file......
  * [ ] A notification system is its own challenge and needs some design

Possible Changes:
* [x] "New group" messaging dialog (i.e. shifting from threads as powerset of members, handle in more friendlier terms of "group chats")
  * [x] As such, allow group chat renaming
  * [x] This could also mean allowing multiple groups per set of users. This fundamentally challenges some of the assumptions that the messaging code makes! See [messaging.models.get_thread](https://github.com/ashbc/tgrsite/blob/bebd6e179dfc4ca2f227f51ae0f99c0731bf6031/messaging/models.py#L28)
* [ ] Change some forms into modals
* [x] Make it so that admins cannot see others' DMs

Bonus Features:
* [x] Gravatar
* [ ] Pizza/food orders
* [ ] Online character sheets widget for LARP
* [ ] ITS SSO for "verified student" on profiles? help cut down on spam / increase accountability?
