### ISSUE TITLE
Issues To Be Completed ASAP

### ISSUE THREAD

**Issue by finnbar** [ashbc/tgrsite#77]
We have a few issues outstanding that should be completed before the end of term. Here they are:

- [ ] #72 - Add links to footer and on registration. Existing users have already been emailed.
- [ ] #74 - Replace Google's generic CAPTCHA with our own bespoke one.
- [ ] #69 - Exec photos system. Probably assign photos to roles and then swap on changeover.
- [ ] #67 - Anon feedback form. Rebranded bugreports.
